"""Seed system subtitle style presets

Revision ID: seed_subtitle_presets_001
Revises: add_subtitle_tables_001
Create Date: 2025-11-11 00:05:00.000000

"""
from typing import Sequence, Union
import json
from datetime import datetime
from uuid import uuid4

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'seed_subtitle_presets_001'
down_revision: Union[str, None] = 'add_subtitle_tables_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Insert system subtitle style presets."""

    # System presets data
    presets = [
        {
            'id': str(uuid4()),
            'name': 'YouTube Default',
            'description': 'Professional YouTube-style subtitles with clean readability',
            'platform': 'youtube',
            'thumbnail_url': None,
            'style_config': json.dumps({
                'font_family': 'Arial',
                'font_size': 32,
                'font_weight': 'bold',
                'font_color': '#FFFFFF',
                'font_alpha': 1.0,
                'background_enabled': False,
                'background_color': '#000000',
                'background_alpha': 0.7,
                'background_padding': 10,
                'background_radius': 0,
                'outline_enabled': True,
                'outline_color': '#000000',
                'outline_width': 2,
                'position_vertical': 'bottom',
                'position_horizontal': 'center',
                'margin_vertical': 50,
                'margin_horizontal': 40,
                'max_width_percent': 80,
                'words_per_line': 7,
                'max_lines': 2,
                'min_display_duration': 1.0,
                'max_display_duration': 6.0,
                'animation_type': 'none',
                'animation_duration': 0.3,
            }),
            'usage_count': 0,
            'is_system_preset': True,
            'is_public': True,
            'created_by': None,
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow(),
        },
        {
            'id': str(uuid4()),
            'name': 'TikTok Viral',
            'description': 'Eye-catching TikTok style with yellow text and black background',
            'platform': 'tiktok',
            'thumbnail_url': None,
            'style_config': json.dumps({
                'font_family': 'Montserrat',
                'font_size': 48,
                'font_weight': 'bold',
                'font_color': '#FFD700',
                'font_alpha': 1.0,
                'background_enabled': True,
                'background_color': '#000000',
                'background_alpha': 0.8,
                'background_padding': 15,
                'background_radius': 8,
                'outline_enabled': False,
                'outline_color': '#000000',
                'outline_width': 0,
                'position_vertical': 'center',
                'position_horizontal': 'center',
                'margin_vertical': 0,
                'margin_horizontal': 40,
                'max_width_percent': 85,
                'words_per_line': 5,
                'max_lines': 3,
                'min_display_duration': 0.8,
                'max_display_duration': 5.0,
                'animation_type': 'pop',
                'animation_duration': 0.2,
            }),
            'usage_count': 0,
            'is_system_preset': True,
            'is_public': True,
            'created_by': None,
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow(),
        },
        {
            'id': str(uuid4()),
            'name': 'Instagram Reels',
            'description': 'Instagram Reels optimized subtitles with rounded background',
            'platform': 'instagram',
            'thumbnail_url': None,
            'style_config': json.dumps({
                'font_family': 'Poppins',
                'font_size': 36,
                'font_weight': 'bold',
                'font_color': '#FFFFFF',
                'font_alpha': 1.0,
                'background_enabled': True,
                'background_color': '#000000',
                'background_alpha': 0.75,
                'background_padding': 12,
                'background_radius': 10,
                'outline_enabled': False,
                'outline_color': '#000000',
                'outline_width': 0,
                'position_vertical': 'bottom',
                'position_horizontal': 'center',
                'margin_vertical': 80,
                'margin_horizontal': 30,
                'max_width_percent': 90,
                'words_per_line': 6,
                'max_lines': 2,
                'min_display_duration': 1.0,
                'max_display_duration': 5.0,
                'animation_type': 'fade',
                'animation_duration': 0.25,
            }),
            'usage_count': 0,
            'is_system_preset': True,
            'is_public': True,
            'created_by': None,
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow(),
        },
        {
            'id': str(uuid4()),
            'name': 'LinkedIn Professional',
            'description': 'Clean professional look for LinkedIn videos',
            'platform': 'linkedin',
            'thumbnail_url': None,
            'style_config': json.dumps({
                'font_family': 'Roboto',
                'font_size': 28,
                'font_weight': 'normal',
                'font_color': '#2D2D2D',
                'font_alpha': 1.0,
                'background_enabled': True,
                'background_color': '#FFFFFF',
                'background_alpha': 0.9,
                'background_padding': 10,
                'background_radius': 4,
                'outline_enabled': False,
                'outline_color': '#000000',
                'outline_width': 0,
                'position_vertical': 'bottom',
                'position_horizontal': 'center',
                'margin_vertical': 60,
                'margin_horizontal': 50,
                'max_width_percent': 75,
                'words_per_line': 8,
                'max_lines': 2,
                'min_display_duration': 1.2,
                'max_display_duration': 6.0,
                'animation_type': 'none',
                'animation_duration': 0.3,
            }),
            'usage_count': 0,
            'is_system_preset': True,
            'is_public': True,
            'created_by': None,
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow(),
        },
        {
            'id': str(uuid4()),
            'name': 'Accessibility High Contrast',
            'description': 'High contrast yellow on black for maximum readability',
            'platform': 'custom',
            'thumbnail_url': None,
            'style_config': json.dumps({
                'font_family': 'Arial',
                'font_size': 40,
                'font_weight': 'bold',
                'font_color': '#FFFF00',
                'font_alpha': 1.0,
                'background_enabled': True,
                'background_color': '#000000',
                'background_alpha': 1.0,
                'background_padding': 15,
                'background_radius': 0,
                'outline_enabled': True,
                'outline_color': '#000000',
                'outline_width': 3,
                'position_vertical': 'bottom',
                'position_horizontal': 'center',
                'margin_vertical': 70,
                'margin_horizontal': 60,
                'max_width_percent': 85,
                'words_per_line': 6,
                'max_lines': 2,
                'min_display_duration': 1.5,
                'max_display_duration': 7.0,
                'animation_type': 'none',
                'animation_duration': 0.3,
            }),
            'usage_count': 0,
            'is_system_preset': True,
            'is_public': True,
            'created_by': None,
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow(),
        },
        {
            'id': str(uuid4()),
            'name': 'Minimalist',
            'description': 'Clean minimalist style with subtle shadow, no background',
            'platform': 'custom',
            'thumbnail_url': None,
            'style_config': json.dumps({
                'font_family': 'Inter',
                'font_size': 24,
                'font_weight': 'normal',
                'font_color': '#FFFFFF',
                'font_alpha': 1.0,
                'background_enabled': False,
                'background_color': '#000000',
                'background_alpha': 0.0,
                'background_padding': 0,
                'background_radius': 0,
                'outline_enabled': True,
                'outline_color': '#000000',
                'outline_width': 1,
                'position_vertical': 'bottom',
                'position_horizontal': 'center',
                'margin_vertical': 40,
                'margin_horizontal': 30,
                'max_width_percent': 80,
                'words_per_line': 8,
                'max_lines': 2,
                'min_display_duration': 1.0,
                'max_display_duration': 6.0,
                'animation_type': 'fade',
                'animation_duration': 0.3,
            }),
            'usage_count': 0,
            'is_system_preset': True,
            'is_public': True,
            'created_by': None,
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow(),
        },
    ]

    # Insert presets
    op.bulk_insert(
        sa.table(
            'subtitle_style_presets',
            sa.column('id', sa.String),
            sa.column('name', sa.String),
            sa.column('description', sa.String),
            sa.column('platform', sa.String),
            sa.column('thumbnail_url', sa.String),
            sa.column('style_config', sa.Text),
            sa.column('usage_count', sa.Integer),
            sa.column('is_system_preset', sa.Boolean),
            sa.column('is_public', sa.Boolean),
            sa.column('created_by', sa.String),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        presets
    )


def downgrade() -> None:
    """Remove system subtitle style presets."""

    # Delete all system presets
    op.execute(
        "DELETE FROM subtitle_style_presets WHERE is_system_preset = true"
    )
